# Generated by Django 4.1.7 on 2024-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=50)),
                ('article_heading', models.CharField(max_length=400)),
                ('article_headlines1', models.CharField(max_length=400)),
                ('article_headlines2', models.CharField(max_length=400)),
                ('article_headlines3', models.CharField(max_length=400)),
                ('article_desc', models.TextField()),
                ('article_pub_date', models.DateField()),
                ('article_category', models.CharField(default='', max_length=50)),
                ('article_subcategory', models.CharField(default='', max_length=50)),
                ('article_published_by', models.CharField(max_length=150)),
                ('article_image1', models.ImageField(default='', upload_to='news/images')),
                ('article_image2', models.ImageField(default='', upload_to='news/images')),
                ('article_image3', models.ImageField(default='', upload_to='news/images')),
                ('article_image4', models.ImageField(default='', upload_to='news/images')),
                ('article_image5', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport1', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport2', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport3', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport4', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport5', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport6', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport7', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport8', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport9', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport10', models.ImageField(default='', upload_to='news/images')),
                ('article_image_casereport11', models.ImageField(default='', upload_to='news/images')),
            ],
        ),
    ]
