# Generated by Django 4.1.7 on 2024-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='article_main_video',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
        migrations.AddField(
            model_name='news_article',
            name='article_report_video1',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
        migrations.AddField(
            model_name='news_article',
            name='article_report_video2',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
        migrations.AddField(
            model_name='news_article',
            name='article_report_video3',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
        migrations.AddField(
            model_name='news_article',
            name='article_report_video4',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
        migrations.AddField(
            model_name='news_article',
            name='article_report_video5',
            field=models.FileField(default='', upload_to='news/videos'),
        ),
    ]
