# Generated by Django 4.1.7 on 2024-05-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_article_article_main_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='article_image1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport10',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport11',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport4',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport5',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport6',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport7',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport8',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_image_casereport9',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_report_video1',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_report_video2',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_report_video3',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_report_video4',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
        migrations.AlterField(
            model_name='news_article',
            name='article_report_video5',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
    ]
