# Generated by Django 4.1.7 on 2024-05-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_article_article_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='article_main_video',
            field=models.FileField(blank=True, default='', null=True, upload_to='news/videos'),
        ),
    ]
