# Generated by Django 4.1.7 on 2024-05-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_article_article_main_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_article',
            name='article_main_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='news/images'),
        ),
    ]
