# Generated by Django 4.1.7 on 2024-05-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_article_article_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_article',
            name='article_main_image',
            field=models.ImageField(default='', upload_to='news/images'),
        ),
    ]
